export const MetadataKeys = {
	IsController: 'isController',
	BasePath: 'basePath',
	ApiTag: 'apiTag',
	Routers: 'routers',
	DestructuringParameter: 'destructuringParameter',
	DestructuringPreParameter: 'destructuringPreParameter',
	ValidationQuery: 'validationQuery',
	ValidationParams: 'validationParams',
	ValidationPayload: 'validationPayload',
	Optional: 'Optional',
	BinaryOptional: 'BinaryOptional',
	Query: 'query',
	Payload: 'payload',
	Params: 'params',
	Middleware: 'middleware',
}
